jobs:
  ci:
    name: Verify
    runs-on: ubuntu-20.04

    steps:
      - name: Initialize
        uses: actions/checkout@v2
      - name: Fetch Tools
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Unit Tests
        run: ./test/ci

name: Workflow

on:
  schedule:
    - cron: "35 */6 * * *"
